### ISSUE TITLE
kuas 10401 schedules

### ISSUE THREAD

**Issue by HuangWenChen** [NKUST-ITC/AP-API#18]
[{'events': ['(9/14)日間部、進修推廣處開學'], 'week':'第一週'}, {'events': ['(9/28)補假一天(補 9/27 中秋節)'], 'week': '第三週'}, {'events': ['(10/9)補假一天(補 10/10 國慶日)'], 'week': '第四週'}, {'events': ['(10/25)校運會','(10/29)校運會補假ㄧ天','(10/30)校慶放假一天'], 'week': '第七週'}, {'events': ['(11/9~11/14)日間部、進修推廣處期中考試'], 'week': '第九週'}, {'events': ['(1/1)開國紀念日放假ㄧ天'], 'week': '第十六週'}, {'events': ['(1/9~1/15)日間部、進修推廣處期末考試'], 'week': '第十八週'}, {'events': ['(1/30)補行上班'], 'week': '第十週'}, {'events': ['(11/26) 燕巢 三合一選舉', '(11/27) 建工 三合一選舉'], 'week': '寒假'}];

**Comment by louisom** [comment]
fixed to json

``` jjson
[{"events": ["(9/14)日間部、進修推廣處開學"], "week": "第一週"}, {"events": ["(9/28)補假一天(補 9/27 中秋節)"], "week": "第三週"}, {"events": ["(10/9)補假一天(補 10/10 國慶日)"], "week": "第四週"}, {"events": ["(10/25)校運會", "(10/29)校運會補假ㄧ天", "(10/30)校慶放假一天"], "week": "第七週"}, {"events": ["(11/9~11/14)日間部、進修推廣處期中考試"], "week": "第九週"}, {"events": ["(1/1)開國紀念日放假ㄧ天"], "week": "第十六週"}, {"events": ["(1/9~1/15)日間部、進修推廣處期末考試"], "week": "第十八週"}, {"events": ["(1/30)補行上班"], "week": "第十週"}, {"events": ["(11/26) 燕巢 三合一選舉", "(11/27) 建工 三合一選舉"], "week": "寒假"}]
```

**Comment by hearsilent** [comment]
https://github.com/kuastw/Calendar-Crawler/blob/master/10401.json
