### ISSUE TITLE
Docs build failed

### ISSUE THREAD

**Issue by whyayen** [NKUST-ITC/AP-API#34]
Error Message:
``ImportError: No module named flask.ext.compress``

We need to change the module name in sphinx 1.5.3 (default version on readthedocs)
Use ``flask_compress`` instead.

**Comment by whyayen** [comment]
@mlouielu  I try to fix it on fork repository.
I don't know should I fix the bug on v2 branch or master ?
Because the documentation website build on v2 branch by readthedocs.

**Comment by mlouielu** [comment]
IIRC is `master` branch, since we used it before.

**Comment by abc873693** [comment]
Fix library error by #36 ,but not build doc.
Will change framework in v3 api.
So close this issue.
