### ISSUE TITLE
SECRET_KEY should not commit to remote

### ISSUE THREAD

**Issue by vn7n24fzkq** [NKUST-ITC/AP-API#39]
https://github.com/NKUST-ITC/AP-API/blob/56d37165f906a2512613cafb129553e7d41c52f5/src/config.py#L4
@abc873693 
Is current api server using this SECRET_KEY ?

**Comment by abc873693** [comment]
It's my fault.

**Comment by abc873693** [comment]
https://github.com/NKUST-ITC/AP-API/commit/56d37165f906a2512613cafb129553e7d41c52f5
