### ISSUE TITLE
 GET /user/graduation-threshold 

### ISSUE THREAD

**Issue by takidog** [NKUST-ITC/AP-API#46]
畢業門檻查詢
雖然在校務系統內，但是連結為ength.kuas.edu.tw 

校務系統 透過func.php  獲取 ength.kuas.edu.tw  cookies

跟其餘的ap query 方法不一樣，先暫時擱置等待其他解法(或是硬A)

**Comment by mlouielu** [comment]
Why close this? Is it implemented? If so, please add some information on it

**Comment by takidog** [comment]
已解決
透過AP cookie 再去登入 ength.kuas.edu.tw


為了接下來v3開的一大堆Issues 也是先整理一下了

**Comment by mlouielu** [comment]
You should always provide a reference (e.g. commit hash, PR number ...etc) or message when closing an issue. Otherwise, people will just get confused about this issue (why it closed? does this issue solve? or the maintainer consider this issue is a won't fix?)
