### ISSUE TITLE
Delete non-exist bus reserve cause HTTP 500

### ISSUE THREAD

**Issue by louisom** [NKUST-ITC/AP-API#8]
Problem from `kuas_api/kuas/bus.py` function `book`

if `kid` isn't exist in unbook, then res will be undefine, thus you can't return a vaild json response.

**Comment by grapherd** [comment]
Fixed 47b7e5e776bbf4106099cb0a6893575c25accfad

**Comment by louisom** [comment]
Fixed 47b7e5e776bbf4106099cb0a6893575c25accfad
