### ISSUE TITLE
AP endpoints ?

### ISSUE THREAD

**Issue by louisom** [NKUST-ITC/AP-API#9]
How to design /v2/ap functions endpoints?

e.g. GET course timetable (學期課表) and GET club activate history  (社團活動紀錄)

GET `/v2/ap/course_timetable`                                 (課表)
GET `/v2/ap/students/course_timetable`                  (學務/課表)
~~GET `/v2/ap/students/queries/course_timetable`      (學務/查詢/課表)~~
~~GET `/v2/ap/queries/course_timetable`                    (查詢/課表)~~
~~GET `/v2/ap/quieries/students/course_timetable`     (查詢/學務/課表)~~

GET `/v2/ap/club_history`                                  (社團活動紀錄)
GET `/v2/acadimics/club_history`                      (教務/社團活動紀錄)
~~GET `/v2/ap/acadimics/queries/club_history`    (教務/查詢/社團活動紀錄)~~
~~GET `/v2/ap/queries/club_history`                     (查詢/社團活動紀錄)~~
~~GET `/v2/ap/queries/academics/club_history`   (查詢/教務/社團活動紀錄)~~

**Comment by hearsilent** [comment]
GET /v2/ap/course/timetable (課表)
GET /v2/acadimics/club_history

**Comment by louisom** [comment]
P.S. students, acadimics says that is under Office of Student Affairs or Office of Academic Affairs

I'll prefer GET `/v2/ap/academics/club_history`
Cause this explicit say that is under AP system (ap.kuas.edu.tw)

But I'm not sure about
GET `/v2/ap/course_timetable` (課表)
GET `/v2/ap/students/course_timetable` (學務/課表)

If we impl 教師課表查詢, it may be
GET `/v2/ap/students/course_timetable`
GET `/v2/ap/students/teacher_course_timetable`

or just
GET `/v2/ap/course_timetable`
GET `/v2/ap/teacher_course_timetable`

**Comment by louisom** [comment]
ref: https://github.com/uWaterloo/api-documentation

**Comment by louisom** [comment]
@hearsilent  Maybe we shoud change url to this?

`/v2/ap/users/cousretables`    (課表)
`/v2/ap/users/activities`          (社團紀錄) not good.

like 

`/v2/ap/users/picture`

**Comment by louisom** [comment]
change to `/v2/ap/users/coursetables/<int:year>/<int:semester>`
